# bot configuration file

# General
# environment variables: development or production
Environment: development
# mode: normal or maintenance
Mode: normal
# command prefix
CommandPrefix: //

# App Commands
# clear app command: if true, the bot will clear all app command on Discord Server
ClearAppCommands: false
# sync command globally: if true, the bot will sync all commands globally
SyncGlobally: false

# Extensions
Extensions:
  - src.extensions.admin
  - src.extensions.kick_and_ban
  - src.extensions.member_count
  - src.extensions.moderation
  - src.extensions.poll
  - src.extensions.utils
