# bot configuration file

# environment variables: development or production
Environment: development

# command prefix
CommandPrefix: //

# clear app command: if true, the bot will clear all app command on Discord Server
clearAppCommands: false
