- ClassName: InquiryView
  CustomId:
    - src.exts.inquiry.InquiryView
  Path: components.cmp_inquiry
- ClassName: Start_Verify_View
  CustomId:
    - components.membership.Start_Verify_View
  Path: components.membership.start_verify
