# - ClassName: InquiryView
#   CustomId:
#     - src.exts.inquiry.InquiryView
#   Path: components.cmp_inquiry
- ClassName: Start_Verify_View
  CustomId:
    - components.membership.Start_Verify_View
  Path: src.components.membership.start_verify
- ClassName: InquiryView
  CustomId:
    - src.extensions.inquiry.send_inquiry_form
  Path: src.components.extensions.inquiry
