# - ClassName: InquiryView
#   CustomId:
#     - src.exts.inquiry.InquiryView
#   Path: components.cmp_inquiry
# TODO: callbackの外部ファイル管理化
- ClassName: InquiryView
  CustomId:
    - src.extensions.inquiry.send_inquiry_form
  Path: src.components.extensions.inquiry
