name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: replace confirm_production_boot
        run: |
          mv src/bot.py src/bot.before.py
          cat src/bot.before.py | sed -e 's/self.confirm_production_boot()/# self.confirm_production_boot()/' > src/bot.py
          diff src/bot.before.py src/bot.py

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
